
frr version 9.1
frr defaults traditional
hostname r4
log syslog informational
service integrated-vtysh-config
!
ip forwarding
no ipv6 forwarding
!
interface lo
  ip address 4.4.4.4/32
!
router ospf

 ospf router-id 4.4.4.4
 network 4.4.4.4/32 area 0.0.0.0
 network 10.0.34.0/24 area 0.0.0.0
 network 10.0.45.0/24 area 0.0.0.0
!
line vty
exit
!
