# frr version 9.1-MyOwnFRRVersion
# frr defaults traditional
# hostname vm-r3
# log syslog informational
# ip forwarding
# no ipv6 forwarding
# service integrated-vtysh-config
frr version 9.1
frr defaults traditional
hostname r3
log syslog informational
service integrated-vtysh-config
!
ip forwarding
no ipv6 forwarding
!
interface lo
  ip address 3.3.3.3/32
!
router ospf

 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0.0.0.0
 network 10.0.23.0/24 area 0.0.0.0
 network 10.0.34.0/24 area 0.0.0.0
!
line vty
exit
!
