frr version 9.1
frr defaults traditional
hostname r2
log syslog informational
service integrated-vtysh-config
!
ip forwarding
no ipv6 forwarding
!
interface lo
  ip address 2.2.2.2/32
!

router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0.0.0.0
 network 10.1.12.0/24 area 0.0.0.0
 network 10.1.23.0/24 area 0.0.0.0
!
line vty
 exit
!
